<?php

use Illuminate\Support\Facades\Lang;

function getCurrencyList()
    {
        $list = collect([
            ['code' =>'AFN' , 'name' => Lang::get('service/currency/list.Afghani'), 'symbol' => '؋'],
            ['code' =>'ALL' , 'name' => Lang::get('service/currency/list.Lek'), 'symbol' => 'Lek' ],
            ['code' =>'ANG' , 'name' => Lang::get('service/currency/list.NetherlandsAntillianGuilder'), 'symbol' => 'ƒ'],
            ['code' =>'ARS' , 'name' => Lang::get('service/currency/list.ArgentinePeso'), 'symbol' => '$'],
            ['code' =>'AUD' , 'name' => Lang::get('service/currency/list.AustralianDollar'), 'symbol' => '$'],
            ['code' =>'AWG' , 'name' => Lang::get('service/currency/list.ArubanGuilder'), 'symbol' => 'ƒ'],
            ['code' =>'AZN' , 'name' => Lang::get('service/currency/list.AzerbaijanianManat'), 'symbol' => 'ман'],
            ['code' =>'BAM' , 'name' => Lang::get('service/currency/list.ConvertibleMarks'), 'symbol' => 'KM'],
            ['code' =>'BBD' , 'name' => Lang::get('service/currency/list.BarbadosDollar'), 'symbol' => '$'],
            ['code' =>'BGN' , 'name' => Lang::get('service/currency/list.BulgarianLev'), 'symbol' => 'лв'],
            ['code' =>'BMD' , 'name' => Lang::get('service/currency/list.BermudianDollar'), 'symbol' => '$'],
            ['code' =>'BND' , 'name' => Lang::get('service/currency/list.BruneiDollar'), 'symbol' => '$'],
            ['code' =>'BOB' , 'name' => Lang::get('service/currency/list.BOVBolivianoMvdol'), 'symbol' => '$b'],
            ['code' =>'BRL' , 'name' => Lang::get('service/currency/list.BrazilianReal'), 'symbol' => 'R$'],
            ['code' =>'BSD' , 'name' => Lang::get('service/currency/list.BahamianDollar'), 'symbol' => '$'],
            ['code' =>'BWP' , 'name' => Lang::get('service/currency/list.Pula'), 'symbol' => 'P'],
            ['code' =>'BYR' , 'name' => Lang::get('service/currency/list.BelarussianRuble'), 'symbol' => 'p.'],
            ['code' =>'BZD' , 'name' => Lang::get('service/currency/list.BelizeDollar'), 'symbol' => 'BZ$'],
            ['code' =>'CAD' , 'name' => Lang::get('service/currency/list.CanadianDollar'), 'symbol' => '$'],
            ['code' =>'CHF' , 'name' => Lang::get('service/currency/list.SwissFranc'), 'symbol' => 'CHF'],
            ['code' =>'CLP' , 'name' => Lang::get('service/currency/list.CLF'), 'symbol' => '$'],
            ['code' =>'CNY' , 'name' => Lang::get('service/currency/list.YuanRenminbi'), 'symbol' => '¥'],
            ['code' =>'COP' , 'name' => Lang::get('service/currency/list.COU'), 'symbol' => '$'],
            ['code' =>'CRC' , 'name' => Lang::get('service/currency/list.CostaRicanColon'), 'symbol' => '₡'],
            ['code' =>'CUP' , 'name' => Lang::get('service/currency/list.CUC'), 'symbol' => '₱'],
            ['code' =>'CZK' , 'name' => Lang::get('service/currency/list.CzechKoruna'), 'symbol' => 'Kč'],
            ['code' =>'DKK' , 'name' => Lang::get('service/currency/list.DanishKrone'), 'symbol' => 'kr'],
            ['code' =>'DOP' , 'name' => Lang::get('service/currency/list.DominicanPeso'), 'symbol' => 'RD$'],
            ['code' =>'EGP' , 'name' => Lang::get('service/currency/list.EgyptianPound'), 'symbol' => '£'],
            ['code' =>'EUR' , 'name' => Lang::get('service/currency/list.Euro'), 'symbol' => '€'],
            ['code' =>'FJD' , 'name' => Lang::get('service/currency/list.FijiDollar'), 'symbol' => '$'],
            ['code' =>'FKP' , 'name' => Lang::get('service/currency/list.FalklandIslandsPound'), 'symbol' => '£'],
            ['code' =>'GBP' , 'name' => Lang::get('service/currency/list.PoundSterling'), 'symbol' => '£'],
            ['code' =>'GIP' , 'name' => Lang::get('service/currency/list.GibraltarPound'), 'symbol' => '£'],
            ['code' =>'GTQ' , 'name' => Lang::get('service/currency/list.Quetzal'), 'symbol' => 'Q'],
            ['code' =>'GYD' , 'name' => Lang::get('service/currency/list.GuyanaDollar'), 'symbol' => '$'],
            ['code' =>'HKD' , 'name' => Lang::get('service/currency/list.HongKongDollar'), 'symbol' => '$'],
            ['code' =>'HNL' , 'name' => Lang::get('service/currency/list.Lempira'), 'symbol' => 'L'],
            ['code' =>'HRK' , 'name' => Lang::get('service/currency/list.CroatianKuna'), 'symbol' => 'kn'],
            ['code' =>'HUF' , 'name' => Lang::get('service/currency/list.Forint'), 'symbol' => 'Ft'],
            ['code' =>'IDR' , 'name' => Lang::get('service/currency/list.Rupiah'), 'symbol' => 'Rp'],
            ['code' =>'ILS' , 'name' => Lang::get('service/currency/list.NewIsraeliSheqel'), 'symbol' => '₪'],
            ['code' =>'IRR' , 'name' => Lang::get('service/currency/list.IranianRial'), 'symbol' => '﷼'],
            ['code' =>'ISK' , 'name' => Lang::get('service/currency/list.IcelandKrona'), 'symbol' => 'kr'],
            ['code' =>'JMD' , 'name' => Lang::get('service/currency/list.JamaicanDollar'), 'symbol' => 'J$'],
            ['code' =>'JPY' , 'name' => Lang::get('service/currency/list.Yen'), 'symbol' => '¥'],
            ['code' =>'KGS' , 'name' => Lang::get('service/currency/list.Som'), 'symbol' => 'лв'],
            ['code' =>'KHR' , 'name' => Lang::get('service/currency/list.Riel'), 'symbol' => '៛'],
            ['code' =>'KPW' , 'name' => Lang::get('service/currency/list.NorthKoreanWon'), 'symbol' => '₩'],
            ['code' =>'KRW' , 'name' => Lang::get('service/currency/list.Won'), 'symbol' => '₩'],
            ['code' =>'KYD' , 'name' => Lang::get('service/currency/list.CaymanIslandsDollar'), 'symbol' => '$'],
            ['code' =>'KZT' , 'name' => Lang::get('service/currency/list.Tenge'), 'symbol' => 'лв'],
            ['code' =>'LAK' , 'name' => Lang::get('service/currency/list.Kip'), 'symbol' => '₭'],
            ['code' =>'LBP' , 'name' => Lang::get('service/currency/list.LebanesePound'), 'symbol' => '£'],
            ['code' =>'LKR' , 'name' => Lang::get('service/currency/list.SriLankaRupee'), 'symbol' => '₨'],
            ['code' =>'LRD' , 'name' => Lang::get('service/currency/list.LiberianDollar'), 'symbol' => '$'],
            ['code' =>'LTL' , 'name' => Lang::get('service/currency/list.LithuanianLitas'), 'symbol' => 'Lt'],
            ['code' =>'LVL' , 'name' => Lang::get('service/currency/list.LatvianLats'), 'symbol' => 'Ls'],
            ['code' =>'MKD' , 'name' => Lang::get('service/currency/list.Denar'), 'symbol' => 'ден'],
            ['code' =>'MNT' , 'name' => Lang::get('service/currency/list.Tugrik'), 'symbol' => '₮'],
            ['code' =>'MUR' , 'name' => Lang::get('service/currency/list.MauritiusRupee'), 'symbol' => '₨'],
            ['code' =>'MXN' , 'name' => Lang::get('service/currency/list.MXVMexicanPesoMexicanUnidaddeInversion(UDI)'), 'symbol' => '$'],
            ['code' =>'MYR' , 'name' => Lang::get('service/currency/list.MalaysianRinggit'), 'symbol' => 'RM'],
            ['code' =>'MZN' , 'name' => Lang::get('service/currency/list.Metical'), 'symbol' => 'MT'],
            ['code' =>'NGN' , 'name' => Lang::get('service/currency/list.Naira'), 'symbol' => '₦'],
            ['code' =>'NIO' , 'name' => Lang::get('service/currency/list.CordobaOro'), 'symbol' => 'C$'],
            ['code' =>'NOK' , 'name' => Lang::get('service/currency/list.NorwegianKrone'), 'symbol' => 'kr'],
            ['code' =>'NPR' , 'name' => Lang::get('service/currency/list.NepaleseRupee'), 'symbol' => '₨'],
            ['code' =>'NZD' , 'name' => Lang::get('service/currency/list.NewZealandDollar'), 'symbol' => '$'],
            ['code' =>'OMR' , 'name' => Lang::get('service/currency/list.RialOmani'), 'symbol' => '﷼'],
            ['code' =>'PAB' , 'name' => Lang::get('service/currency/list.USDBalboaUSDollar'), 'symbol' => 'B/.'],
            ['code' =>'PEN' , 'name' => Lang::get('service/currency/list.NuevoSol'), 'symbol' => 'S/.'],
            ['code' =>'PHP' , 'name' => Lang::get('service/currency/list.PhilippinePeso'), 'symbol' => 'Php'],
            ['code' =>'PKR' , 'name' => Lang::get('service/currency/list.PakistanRupee'), 'symbol' => '₨'],
            ['code' =>'PLN' , 'name' => Lang::get('service/currency/list.Zloty'), 'symbol' => 'zł'],
            ['code' =>'PYG' , 'name' => Lang::get('service/currency/list.Guarani'), 'symbol' => 'Gs'],
            ['code' =>'QAR' , 'name' => Lang::get('service/currency/list.QatariRial'), 'symbol' => '﷼'],
            ['code' =>'RON' , 'name' => Lang::get('service/currency/list.NewLeu'), 'symbol' => 'lei'],
            ['code' =>'RSD' , 'name' => Lang::get('service/currency/list.SerbianDinar'), 'symbol' => 'Дин.'],
            ['code' =>'RUB' , 'name' => Lang::get('service/currency/list.RussianRuble'), 'symbol' => 'руб'],
            ['code' =>'SAR' , 'name' => Lang::get('service/currency/list.SaudiRiyal'), 'symbol' => '﷼'],
            ['code' =>'SBD' , 'name' => Lang::get('service/currency/list.SolomonIslandsDollar'), 'symbol' => '$'],
            ['code' =>'SCR' , 'name' => Lang::get('service/currency/list.SeychellesRupee'), 'symbol' => '₨'],
            ['code' =>'SEK' , 'name' => Lang::get('service/currency/list.SwedishKrona'), 'symbol' => 'kr'],
            ['code' =>'SGD' , 'name' => Lang::get('service/currency/list.SingaporeDollar'), 'symbol' => '$'],
            ['code' =>'SHP' , 'name' => Lang::get('service/currency/list.SaintHelenaPound'), 'symbol' => '£'],
            ['code' =>'SOS' , 'name' => Lang::get('service/currency/list.SomaliShilling'), 'symbol' => 'S'],
            ['code' =>'SRD' , 'name' => Lang::get('service/currency/list.SurinamDollar'), 'symbol' => '$'],
            ['code' =>'SVC' , 'name' => Lang::get('service/currency/list.USDElSalvadorColonUSDollar'), 'symbol' => '$'],
            ['code' =>'SYP' , 'name' => Lang::get('service/currency/list.SyrianPound'), 'symbol' => '£'],
            ['code' =>'THB' , 'name' => Lang::get('service/currency/list.Baht'), 'symbol' => '฿'],
            ['code' =>'TRY' , 'name' => Lang::get('service/currency/list.TurkishLira'), 'symbol' => 'TL'],
            ['code' =>'TTD' , 'name' => Lang::get('service/currency/list.TrinidadandTobagoDollar'), 'symbol' => 'TT$'],
            ['code' =>'TWD' , 'name' => Lang::get('service/currency/list.NewTaiwanDollar'), 'symbol' => 'NT$'],
            ['code' =>'UAH' , 'name' => Lang::get('service/currency/list.Hryvnia'), 'symbol' => '₴'],
            ['code' =>'USD' , 'name' => Lang::get('service/currency/list.USDollar'), 'symbol' => '$'],
            ['code' =>'UYU' , 'name' => Lang::get('service/currency/list.UYIPesoUruguayoUruguayPesoenUnidadesIndexadas'), 'symbol' => '$U'],
            ['code' =>'UZS' , 'name' => Lang::get('service/currency/list.UzbekistanSum'), 'symbol' => 'лв'],
            ['code' =>'VEF' , 'name' => Lang::get('service/currency/list.BolivarFuerte'), 'symbol' => 'Bs'],
            ['code' =>'VND' , 'name' => Lang::get('service/currency/list.Dong'), 'symbol' => '₫'],
            ['code' =>'XCD' , 'name' => Lang::get('service/currency/list.EastCaribbeanDollar'), 'symbol' => '$'],
            ['code' =>'YER' , 'name' => Lang::get('service/currency/list.YemeniRial'), 'symbol' => '﷼'],
            ['code' =>'ZAR' , 'name' => Lang::get('service/currency/list.Rand'), 'symbol' => 'R'],
            ]);
        return $list;

}


