<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $table = 'cars';
    protected $fillable = [
        'vin',
        'model_id',
        'bought_price',
        'sold_price',
        'from',
        'offer_id',
        'customer_id',
        'bought_date',
        'in_warehouse_date',
        'sold_date',
        'left_warehouse_date',
        'extra',
        'sold_currency',
        'bought_currency'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function model() {
      return $this->belongsTo('App\Models\CarModel');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function customer() {
        return $this->belongsTo('App\Models\Customer');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function transport() {
        return $this->belongsTo('App\Models\Transport');
    }

    /**
     * Checking status of process
     * if 1 then car was just bought
     * 2 if bought and is in warehouse
     * 3 if bought and sold but didn't left warehouse
     * 4 if bought sold but didn't came to warehouse yet
     * 5 if selling process is done
     * 6 if car stuck longer than 30 days and somehow in warehouse or was sold but didn't came to warehouse yet
     * or when is over 60 days and car stuck somewhere after purchase
     * @return int
     */
    public function status() {
        if(isset($this->bought_date)){
            $status = 1;
        }
        if(isset($this->bought_date) && isset($this->in_warehouse_date)){
            $status = 2;
        }
        if(isset($this->bought_date) && isset($this->in_warehouse_date) && isset($this->sold_date)){
            $status = 3;
        }
        if(isset($this->bought_date) && !isset($this->in_warehouse_date) && isset($this->sold_date)){
            $status = 4;
        }
        if(isset($this->bought_date) && isset($this->in_warehouse_date) && isset($this->sold_date)
            && isset($this->left_warehouse_date)) {
            $status = 5;
        }
        if(isset($this->bought_date) && $this->bought_date<Carbon::now()->subDays(30)->toDateTimeString()
            && !isset($this->sold_date)){
            $status = 6;
        }
        if(isset($this->bought_date) && $this->bought_date<Carbon::now()->subDays(30)->toDateTimeString()
            && isset($this->sold_date) && !isset($this->in_warehouse_date)){
            $status = 6;
        }
        if(isset($this->bought_date) && $this->bought_date<Carbon::now()->subDays(60)->toDateTimeString()){
            $status = 6;
        }

        return $status;
    }


    /**
     * taking ID from string generated by autocomplete
     * @param $string
     * @return mixed
     */
    public static function takeId($string) {
        $id = explode('#', $string);
        $id = explode(' ', $id[1]);
        $result = $id[0];

        return $result;
    }
}
